development:
  adapter: postgresql
  encoding: unicode
  database: edge_development
  pool: 5
  username: postgres
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: edge_test
  pool: 5
  username: postgres
  password: 